"""
WSS-MQTT API 상수 정의.

사양서 8절 타임아웃 정책 및 7절 에러 코드를 반영한다.
"""

# 타임아웃 (초)
# 사양 8.1: ACK 수신 대기 시간
ACK_TIMEOUT_DEFAULT = 5.0

# 구독 큐 최대 크기 (무한 증가 방지, None이면 제한 없음)
SUBSCRIPTION_QUEUE_MAXSIZE_DEFAULT = 10_000

# 연결 끊김 sentinel (구독 스트림 queue에 투입하여 대기 중인 consumer에 알림)
CONNECTION_CLOSED_SENTINEL = object()
# 사양 8.2: RPC 응답 대기 시간 (제어 명령 → 응답 토픽 구독)
RPC_RESPONSE_TIMEOUT_DEFAULT = 30.0

# HTTP 상태 코드 (ACK code)
CODE_OK = 200
CODE_BAD_REQUEST = 400
CODE_UNAUTHORIZED = 401
CODE_FORBIDDEN = 403
CODE_UNPROCESSABLE_ENTITY = 422
CODE_GATEWAY_TIMEOUT = 504

# 이벤트 유형
EVENT_ACK = "ACK"
EVENT_SUBSCRIPTION = "SUBSCRIPTION"

# 액션 유형
ACTION_PUBLISH = "PUBLISH"
ACTION_SUBSCRIBE = "SUBSCRIBE"
ACTION_UNSUBSCRIBE = "UNSUBSCRIBE"
